version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: agence-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dev_password_123
      MONGO_INITDB_DATABASE: agence_immobiliere_dev
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - agence-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: agence-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:dev_password_123@mongodb:27017/agence_immobiliere_dev?authSource=admin
      JWT_SECRET: dev_super_secret_key_change_in_production_123456789
      JWT_EXPIRE: 7d
      CLIENT_URL: http://localhost:3000
      API_URL: http://localhost:5000
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend-logs:/app/logs
    networks:
      - agence-network
    stdin_open: true
    tty: true
    command: npm run dev

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: agence-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      WATCHPACK_POLLING: "true"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - agence-network
    stdin_open: true
    tty: true
    command: npm run dev

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local
  backend-logs:
    driver: local

networks:
  agence-network:
    driver: bridge
    name: agence-network
